---
version: 2.1

orbs:
  release-management: salesforce/npm-release-management@4

jobs:
  lint: &lint
    docker:
      - image: node:latest
    # environment:
    #   - TEST_SERIES: 1
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - cache-{{checksum ".circleci/config.yml"}}-{{ checksum "yarn.lock"}}
            - cache-{{checksum ".circleci/config.yml"}}
      - run: yarn add -D mocha-junit-reporter@1
      - run: yarn exec nps lint
      - persist_to_workspace: {root: node_modules,  paths: ["*"]}
  compile-typescript:
    <<: *lint
    steps:
      - checkout
      - restore_cache: *restore_cache
      - attach_workspace: {at: node_modules}
      - run: yarn
      - run: rm -rf lib && npx tsc --noEmit && rm -fr lib
  test:
    <<: *lint
    parameters:
      image:
        type: string
    docker:
      - image: << parameters.image >>
    steps:
      - checkout
      - restore_cache: *restore_cache
      - attach_workspace: {at: node_modules}
      - run: .circleci/setup_git
      - run: yarn exec nps test
      - store_test_results:
          path: ~/cli/reports
  node-devcli: &node-devcli
    docker:
      - image: node:latest
    working_directory: ~/cli
    environment:
      NYC: "yarn exec nyc -- --nycrc-path node_modules/@oclif/nyc-config/.nycrc"
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - cache-{{checksum ".circleci/config.yml"}}-{{ checksum "yarn.lock"}}
            - cache-{{checksum ".circleci/config.yml"}}
      - run: 'echo "Node: `node --version`"'
      - run: yarn
      - run: .circleci/loadgpg
      - run: yarn add -D nyc@13 @oclif/nyc-config@1
      - run: ./node_modules/.bin/tsc
      - run: ./bin/run --version
      - run: ./bin/run --help

  cache:
    <<: *lint
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
      - run: yarn add -D mocha-junit-reporter@1
      - run: yarn install
      - save_cache:
          key: cache-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
          paths:
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn
workflows:
  version: 2
  oclif:
    jobs:
      - lint
      - compile-typescript
      - node-devcli
      - test:
          matrix:
            parameters:
              image: [node:latest, node:16, node:14]
          name: test-<< matrix.image >>
          requires: [lint, compile-typescript]
      - release-management/release-package:
          context: org-global
          github-release: false
          prerelease: true
          tag: dev
          requires:
            - lint
            - compile-typescript
            - node-devcli
            - test
          filters:
            branches:
              only: re/additional_executables
      - cache: {requires: [release-management/release-package]}
