name: automerge
on:
  workflow_dispatch:
  schedule:
    - cron: '17 2,5,8,11 * * *'

jobs:
  automerge:
    uses: salesforcecli/github-workflows/.github/workflows/automerge.yml@main
    secrets:
      SVC_CLI_BOT_GITHUB_TOKEN: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}
